name: Deploy images AlmaLinux 9

on:
  workflow_dispatch:
    inputs:
      build_only:
        description: Build only? (true|false)
        required: false
        default: 'false'
      specific_job:
        description: Run a specific job? (c8-py37)
        required: false
        default: ''

jobs:
  a9-py37:
    if: ${{ github.event.inputs.specific_job == '' || contains(github.event.inputs.specific_job, 'a9-py37') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up QEMU 🌈
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx ✨
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub 🎪
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and deploy image 🐳
        uses: docker/build-push-action@v4
        with:
          context: docker
          file: docker/Dockerfile_alma9_py37
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event.inputs.build_only != 'true' }}
          tags: riga/law:a9-py37
